### PR TITLE
Transcript

### PR DESCRIPTION
**Pull request by nelsonic**
Hi @rtfeldman,
Hope you are well! 😊 
as part of https://github.com/rtfeldman/elm-workshop/issues/8 
please find attached the transcript for the ***first 8 minutes*** of video `h1.mp4`. ✅ 

Sadly I'm quite **Time Poor** right now. ⏳ 
Hopefully other people can pick this up and help _make_ "***2017 - The Year of Elm***"!
Thanks again for your superb content! ❤️

### CODE REVIEW

**Comment by rtfeldman** [comment]
Hey, it's a start! Thank you @nelsonic!

**Comment by rtfeldman** [comment]
btw @nelsonic I noticed you and @iteles are in London...I'll be there for QCon in March, would be happy to meet up if we can make the schedules work out! 😄

**Comment by nelsonic** [comment]
Hi @rtfeldman thanks for reviewing/merging the PR. 👍 
we would _love_ to meet up when you're in London! 🇬🇧 
we will `make` our schedule work. 📆  ✅ 

Out of interest are you doing a `new` _talk_ at QCon? 🤔 
e.g: "_**18 Months** of Elm in Production_"...? 🎉 
We went a couple of years ago, but weren't _planning_ on going this year... 💸 
(_unless there was a **elmazing** reason to go..._) 😉 

Thanks again! ❤️

**Comment by rtfeldman** [comment]
Yes, doing [a new talk](https://qconlondon.com/users/richard-feldman) at QCon! Let's chat on Elm Slack about further details. 😄

**Pull request merged**
